name: riverpod_playground
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  riverpod_sqflite: ^0.4.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  path: ^1.9.0
  uuid: ^4.5.2
  drift: ^2.29.0
  drift_flutter: ^0.2.8
  path_provider: ^2.1.5
  clock: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true
