name: riverpod_playground
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  riverpod_sqflite: ^0.1.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite: ^2.4.2
  path: ^1.9.0
  uuid: ^4.5.1
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  clock: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.0-dev.16
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^3.0.0-dev.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.27.0

flutter:
  uses-material-design: true
